name: repo_dispatch_test

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo_dispatch_test
      env:
        GITLAB_URL: "https://gitlab.cern.ch/vavolkl/ci-mirror-test"
        GITLAB_HOSTNAME: "gitlab.cern.ch"
        GITLAB_PASSWORD2: ${{ secrets.GITLAB_PASSWORD2 }}
        GITLAB_PROJECT_ID: 94349
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POLL_TIMEOUT: 25
      run: |
        echo "gls:"
        echo ${{ secrets.GITLAB_PASSWORD2 }}
        #./.github/scripts/gitlabmirror.sh
